# Generated by Django 2.1.5 on 2019-01-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRawData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=60)),
                ('away_team', models.CharField(max_length=60)),
                ('full_time_home_goals', models.IntegerField()),
                ('full_time_away_goals', models.IntegerField()),
                ('full_time_result', models.FloatField()),
                ('half_time_home_goals', models.IntegerField()),
                ('half_time_away_goals', models.IntegerField()),
                ('half_time_result', models.FloatField()),
                ('attendance', models.IntegerField()),
                ('home_shots', models.IntegerField()),
                ('away_shots', models.IntegerField()),
                ('home_woodwork_hits', models.IntegerField()),
                ('away_woodwork_hits', models.IntegerField()),
                ('home_corners', models.IntegerField()),
                ('away_corners', models.IntegerField()),
                ('home_fouls_commited', models.IntegerField()),
                ('away_fouls_commited', models.IntegerField()),
                ('home_offsides', models.IntegerField()),
                ('away_offsides', models.IntegerField()),
                ('home_red_cards', models.IntegerField()),
                ('away_red_cards', models.IntegerField()),
                ('home_yellow_cards', models.IntegerField()),
                ('away_yellow_cards', models.IntegerField()),
            ],
        ),
    ]
