# Generated by Django 2.1.5 on 2019-01-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5)),
                ('home_team', models.CharField(max_length=60)),
                ('away_team', models.CharField(max_length=60)),
                ('home_form', models.FloatField()),
                ('away_form', models.FloatField()),
                ('result', models.FloatField()),
                ('home_concentration', models.FloatField()),
                ('away_concentration', models.FloatField()),
                ('goal_diff', models.FloatField()),
                ('score_diff', models.FloatField()),
                ('history', models.FloatField()),
                ('home_motivation', models.FloatField()),
                ('away_motivation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('season', models.CharField(max_length=5, null=True)),
                ('home_team', models.CharField(max_length=60)),
                ('away_team', models.CharField(max_length=60)),
                ('full_time_home_goals', models.IntegerField()),
                ('full_time_away_goals', models.IntegerField()),
                ('full_time_result', models.FloatField()),
                ('half_time_home_goals', models.IntegerField(null=True)),
                ('half_time_away_goals', models.IntegerField(null=True)),
                ('half_time_result', models.FloatField(null=True)),
                ('attendance', models.IntegerField(null=True)),
                ('home_shots', models.IntegerField(null=True)),
                ('away_shots', models.IntegerField(null=True)),
                ('home_woodwork_hits', models.IntegerField(null=True)),
                ('away_woodwork_hits', models.IntegerField(null=True)),
                ('home_corners', models.IntegerField(null=True)),
                ('away_corners', models.IntegerField(null=True)),
                ('home_fouls_commited', models.IntegerField(null=True)),
                ('away_fouls_commited', models.IntegerField(null=True)),
                ('home_offsides', models.IntegerField(null=True)),
                ('away_offsides', models.IntegerField(null=True)),
                ('home_red_cards', models.IntegerField(null=True)),
                ('away_red_cards', models.IntegerField(null=True)),
                ('home_yellow_cards', models.IntegerField(null=True)),
                ('away_yellow_cards', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5)),
                ('team', models.CharField(max_length=60)),
                ('round_start', models.DateField(null=True)),
                ('round_end', models.DateField(null=True)),
                ('wins', models.IntegerField(null=True)),
                ('draws', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('goals_scored', models.IntegerField(null=True)),
                ('goals_received', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seasontables',
            unique_together={('season', 'team', 'round_start', 'round_end')},
        ),
        migrations.AlterUniqueTogether(
            name='matchrawdata',
            unique_together={('date', 'home_team', 'away_team')},
        ),
        migrations.AlterUniqueTogether(
            name='extractedfixtures',
            unique_together={('season', 'home_team', 'away_team')},
        ),
    ]
