# Generated by Django 2.1.5 on 2019-01-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrawdata',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='away_corners',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='away_fouls_commited',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='away_offsides',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='away_red_cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='away_shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='away_woodwork_hits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='away_yellow_cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='half_time_away_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='half_time_home_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='half_time_result',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='home_corners',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='home_fouls_commited',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='home_offsides',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='home_red_cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='home_shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='home_woodwork_hits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrawdata',
            name='home_yellow_cards',
            field=models.IntegerField(null=True),
        ),
    ]
