# Generated by Django 2.1.5 on 2019-01-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190114_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrawdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
