# Generated by Django 2.1.5 on 2019-01-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190114_0921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchrawdata',
            unique_together={('date', 'home_team', 'away_team')},
        ),
    ]
