# Generated by Django 2.1.5 on 2019-01-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190115_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrawdata',
            name='season',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
