# Generated by Django 2.1.5 on 2019-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_matchrawdata_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5)),
                ('home_team', models.CharField(max_length=60)),
                ('away_team', models.CharField(max_length=60)),
                ('home_form', models.FloatField()),
                ('away_form', models.FloatField()),
                ('result', models.FloatField()),
                ('home_concentration', models.FloatField()),
                ('away_concentration', models.FloatField()),
                ('goal_diff', models.FloatField()),
                ('score_diff', models.FloatField()),
                ('history', models.FloatField()),
                ('home_motivation', models.FloatField()),
                ('away_motivation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=5, null=True)),
                ('team', models.CharField(max_length=60)),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_received', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='extractedfixtures',
            unique_together={('season', 'home_team', 'away_team')},
        ),
    ]
