# Generated by Django 2.1.5 on 2019-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190119_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasontables',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasontables',
            name='goals_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasontables',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasontables',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasontables',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasontables',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
